name: 'Setup Mock Amplify Config'
description: 'Creates a mock amplify_outputs.json for CI/CD builds'
runs:
  using: "composite"
  steps:
    - name: Create mock Amplify outputs
      shell: bash
      run: |
        cat > amplify_outputs.json << 'EOF'
        {
          "version": "1.4",
          "auth": {
            "aws_region": "us-east-2",
            "user_pool_id": "mock-pool-id",
            "user_pool_client_id": "mock-client-id",
            "identity_pool_id": "us-east-2:mock-identity-pool",
            "password_policy": {
              "min_length": 8,
              "require_lowercase": false,
              "require_uppercase": false,
              "require_numbers": false,
              "require_symbols": false
            },
            "standard_required_attributes": ["email"],
            "username_attributes": ["email"],
            "user_verification_types": ["email"],
            "mfa_configuration": "NONE",
            "mfa_methods": []
          }
        }
        EOF
